services:
  api:
    build:
      context: .
      target: dev
    environment:
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=hTae9VsSoy86uKZ
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    command: ./bin/server
    ports:
      - 5000:5000
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hTae9VsSoy86uKZ
      - POSTGRES_DB=crebitos
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    postgres:
