services:
  api:
    build:
      context: .
      target: build
    environment:
      - DATABASE_URL=postgresql://admin:hTae9VsSoy86uKZ@db:5432/crebitos
      - RACK_ENV=development
    depends_on:
      - db
    command: ./bin/server
    ports:
      - 5000:5000
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hTae9VsSoy86uKZ
      - POSTGRES_DB=crebitos
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
    postgres:
