services:
  api:
    build:
      context: .
      target: build
    environment:
      - DATABASE_URL=postgresql://admin:hTae9VsSoy86uKZ@db:5432/crebitos
      - RACK_ENV=development
    command: ./bin/server
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hTae9VsSoy86uKZ
      - POSTGRES_DB=crebitos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crebitos -h 0.0.0.0 -p 5432"]
      interval: 3s
      timeout: 3s
      retries: 5
